languageCode = "ja-JP"
baseurl = "https://gurimusan.github.io/blog/"
title = "gurimusan blog"
canonifyurls = true
theme = "slim"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

[permalinks]
  post = "/:year/:month/:title/"
